apiVersion: v1
kind: Service
metadata:
  name: {{ include "fed-model.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.model.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.model.name }}
