services:
  minio:
    image: minio/minio:latest
    container_name: minio-silo1
    user: "0:0"  # root 사용자로 실행 (권한 문제 해결)
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - /var/lib/docker/data/minio:/data
    networks:
      - minio-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  minio-net:
    driver: bridge

